name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - api-flask

env:
  AZURE_WEBAPP_NAME: textanalysis
  AZURE_WEBAPP_PACKAGE_PATH: '.'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create and start virtual environment
      run: |
          python -m venv venv
          source venv/bin/activate

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: python -m unittest test_api.py

    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
