name: Build and deploy Python app to Azure Web App

on:
  push:
    branches:
      - api-flask

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Create and start virtual environment
      run: |
          python -m venv venv
          source venv/bin/activate
      
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: python -m unittest test_api.py

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'textanalysis'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
